"""
Django settings for rentera project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-otaud1pk@)@y=r==11p#j72%s&u_2@3soojf(*f#)9y3*=yr(9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rentals',
    'rest_framework',
    'proprietor',
    'renter' 
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'rentals.middlewares.CustomSessionCookieMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',      #customsessioncookie must be before authenticationmiddleware as authentication one works on request.user which is passed via a session
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rentals.middlewares.CleanupExpiredPropertiesMiddleware',           #for auitomatic expiry of property
]

ROOT_URLCONF = 'rentera.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rentera.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build')  # For collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# to show logs in terminal
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {  # Handler to print to terminal
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # Show DEBUG and above
    },
}


#email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER='unxaun@gmail.com'#USER GMAIL TO SEND MAIL
EMAIL_HOST_PASSWORD= "jzpl nwvj gnle eboq"#GIVE THE APP PASSWORD
DEFAULT_FROM_EMAIL = 'no-reply@yourdomain.com'

ADMIN_EMAIL = 'unxaun@gmail.com'

# For the Admin side (you may want different expiration or settings)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30 # Set for 1 day, adjust as needed
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists until expiry


# For User-side (also can be customized if needed)
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name for regular users


JAZZMIN_SETTINGS={
    'site_header':"Rentera",
    'site_brand':"Rentera",
    'site_logo':"static/img/logo.png",
    'copyright':"rentera.com",
}

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rentals',
    'proprietor',
    'renter',
    'paypal.standard.ipn',
]
#paypal settings
#set sandbox to true
PAYPAL_TEST=True
PAYPAL_RECEIVER_EMAIL="unxaun@gmail.com"    #business acc
PAYPAL_CLIENT_ID = 'AZLJNIQ6C5UHvhfOviGWLjgAoR9QYwW9QvElB3ZJBG8YUWPqbjQbqpvo1SiYvnoGqaNWkN7sWfo6zIin'
PAYPAL_CLIENT_SECRET = 'ENhsSDu2l-_4iiFdjJoTvVtjvBZrjinysIfoXh3yvslsjsgR610Z1BJk4oUuJLvROCL5MDV4YnZ7kC7h'

#esewa integartion
''' ESEWA_MERCHANT_ID = "EPAYTEST"
ESEWA_BASE_URL = "https://uat.esewa.com.np/epay/main"
ESEWA_VERIFY_URL = "https://uat.esewa.com.np/epay/transrec"
 '''

ESEWA_MERCHANT_ID = "EPAYTEST"
ESEWA_SECRET_KEY = "8gBm/:&EnhH.1/q"
ESEWA_PRODUCT_CODE = "EPAYTEST"

ESEWA_V2_PAYMENT_URL = "https://rc-epay.esewa.com.np/api/epay/main/v2/form"
ESEWA_V2_VERIFY_URL = "https://rc-epay.esewa.com.np/api/epay/transaction/status/"


