# Generated by Django 5.2.3 on 2025-12-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0007_merge_20251129_1616'),
        ('rentals', '0002_passwordresetotp'),
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='proprietor.property')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='rentals.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'property')},
            },
        ),
    ]
