# Generated by Django 5.2.3 on 2025-10-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('Municipality', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ward_no', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(max_length=255)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='backups/')),
                ('is_verified', models.BooleanField(default=False)),
                ('sheet_no', models.CharField(blank=True, max_length=100, null=True)),
                ('land_no', models.CharField(blank=True, max_length=100, null=True)),
                ('backup_created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Land_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('citizenship_number', models.CharField(max_length=14)),
                ('land_no', models.PositiveIntegerField(blank=True, null=True)),
                ('sheet_no', models.PositiveIntegerField(blank=True, null=True)),
                ('province', models.CharField(choices=[('1', 'Province No. 1 (Koshi)'), ('2', 'Province No. 2 (Madhesh)'), ('3', 'Province No. 3 (Bagmati)'), ('4', 'Province No. 4 (Gandaki)'), ('5', 'Province No. 5 (Lumbini)'), ('6', 'Province No. 6 (Karnali)'), ('7', 'Province No. 7 (Sudurpashchim)')], max_length=30)),
                ('Municipality', models.CharField(blank=True, max_length=300, null=True)),
                ('District', models.CharField(max_length=100)),
                ('ward_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental House land Record',
                'verbose_name_plural': 'Land Records',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('1', 'Province No. 1 (Koshi)'), ('2', 'Province No. 2 (Madhesh)'), ('3', 'Province No. 3 (Bagmati)'), ('4', 'Province No. 4 (Gandaki)'), ('5', 'Province No. 5 (Lumbini)'), ('6', 'Province No. 6 (Karnali)'), ('7', 'Province No. 7 (Sudurpashchim)')], max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('Municipality', models.CharField(blank=True, max_length=300, null=True)),
                ('District', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ward_no', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('room', 'Room'), ('house', 'House'), ('flat and apartment', 'Flat and Apartment'), ('office space', 'Office Space'), ('shutters and shops', 'Shutters and Shops')], max_length=30)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='propert_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('sheet_no', models.PositiveIntegerField(blank=True, null=True)),
                ('land_no', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
