# Generated by Django 5.2.3 on 2025-10-14 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietor', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupproperty',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.userprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.ManyToManyField(to='proprietor.facility'),
        ),
        migrations.AddField(
            model_name='property',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.userprofile'),
        ),
    ]
