# Generated by Django 5.2.3 on 2025-11-29 02:53

import django.db.models.deletion
import proprietor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=proprietor.models.property_media_upload_path, validators=[proprietor.models.validate_media_file])),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='proprietor.property')),
            ],
        ),
    ]
