# Generated by Django 5.2.3 on 2025-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupproperty',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
