# Generated by Django 5.2.3 on 2025-10-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0003_backupproperty_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupproperty',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='proprietor.facility'),
        ),
    ]
