# Generated by Django 5.2.3 on 2025-10-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0004_backupproperty_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='backup_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
