# Generated by Django 5.2.3 on 2025-10-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0005_property_backup_expires_at_property_is_expired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupProperty',
        ),
    ]
