# Generated by Django 5.2.3 on 2025-11-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0003_remove_property_image_propertymedia'),
        ('proprietor', '0006_delete_backupproperty'),
    ]

    operations = [
    ]
